# Generated by Django 5.0.2 on 2024-03-03 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_pirepsflight_aircraft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pirepsflight',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='pirepsflight',
            name='flight_type',
        ),
        migrations.AddField(
            model_name='pirepsflight',
            name='event',
            field=models.CharField(choices=[('Não', 'Não'), ('Sim', 'Sim')], default='Não', max_length=50),
        ),
        migrations.AlterField(
            model_name='pirepsflight',
            name='route',
            field=models.TextField(blank=True, null=True),
        ),
    ]
