# Generated by Django 5.0.2 on 2024-03-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_pirepsflight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='event',
            field=models.CharField(choices=[('n', 'Não'), ('s', 'Sim')], default='nao', max_length=3),
        ),
    ]
