# Generated by Django 5.0.2 on 2024-03-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_alter_pirepsflight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='event',
            field=models.CharField(choices=[('N', 'Não'), ('S', 'Sim')], max_length=50),
        ),
    ]
