# Generated by Django 5.0.2 on 2024-03-19 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_evento_agendamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamento',
            name='usernames',
        ),
    ]
