# Generated by Django 5.0.2 on 2024-03-20 23:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_remove_agendamento_usernames'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='link_evento',
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='piloto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agendamentos', to=settings.AUTH_USER_MODEL),
        ),
    ]
