# Generated by Django 5.0.2 on 2024-03-21 22:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_evento_link_evento_alter_agendamento_piloto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='piloto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Piloto'),
        ),
    ]
