# Generated by Django 5.0.2 on 2024-03-21 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_alter_agendamento_piloto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agendamento',
            name='status',
            field=models.CharField(blank=True, choices=[('Partida Verde', 'Partida Verde'), ('Pousou Verde', 'Pousou Verde'), ('Partida Amarelo', 'Partida Amarelo'), ('Pousou Amarelo', 'Pousou Amarelo'), ('Partida Vermelho', 'Partida Vermelho'), ('Pousou Vermelho', 'Pousou Vermelho'), ('Agendado Cinza', 'Agendado Cinza'), ('Estimado Verde', 'Estimado Verde'), ('Cancelado Vermelho', 'Cancelado Vermelho')], default='Agendado Cinza', max_length=200, verbose_name='Status'),
        ),
    ]
