# Generated by Django 5.0.2 on 2024-09-18 19:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_remove_award_allowed_aircraft_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PilotAward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=300, null=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('participants', models.ManyToManyField(blank=True, related_name='pilot_awards', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
