# Generated by Django 5.0.2 on 2024-09-21 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0035_rename_icao_award_icao_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='pirepsflight',
            name='flight_icao',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
