# Generated by Django 5.0.2 on 2024-09-21 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_pirepsflight_flight_icao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='flight_duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
