# Generated by Django 5.0.2 on 2024-03-04 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_pirepsflight_airline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='event',
            field=models.CharField(choices=[('nao', 'Não'), ('sim', 'Sim')], default='nao', max_length=3),
        ),
    ]
