# Generated by Django 5.0.2 on 2024-03-14 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_alter_pirepsflight_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pirepsflight',
            name='event',
            field=models.CharField(choices=[('sim', 'Sim'), ('nao', 'Não')], max_length=50),
        ),
    ]
