# Generated by Django 5.0.2 on 2024-03-20 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_remove_evento_link_evento_alter_agendamento_piloto'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='link_evento',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='agendamento',
            name='piloto',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Piloto'),
        ),
    ]
