# Generated by Django 5.0.2 on 2024-05-31 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_award_allowed_aircraft_award_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='award',
            name='start_date',
        ),
        migrations.AddField(
            model_name='useraward',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='useraward',
            name='start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
