# Generated by Django 5.0.2 on 2024-06-01 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_remove_award_end_date_remove_award_start_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='link_image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
