# Generated by Django 5.0.2 on 2024-09-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_pilotaward'),
    ]

    operations = [
        migrations.AddField(
            model_name='award',
            name='icao',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
