# Generated by Django 5.0.2 on 2024-09-20 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_award_icao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='award',
            old_name='icao',
            new_name='icao_company',
        ),
    ]
