# Generated by Django 5.0.2 on 2024-09-22 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_alter_pirepsflight_flight_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='award',
            name='icao_company',
        ),
        migrations.CreateModel(
            name='AllowedIcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_icao', models.CharField(max_length=5)),
                ('award', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_icao', to='accounts.award')),
            ],
        ),
    ]
